"""
Fig 6: UV-completion parameter-space bounds.

Translates the halo-derived $(\Lambda, m_\chi)$ bounds of Sec.~IV onto the
native parameter spaces of the two illustrative UV completions considered in
Sec.~V:

* **Dark-Higgs portal** — the fermionic Rayleigh operator is generated at
  low energy by integrating out a heavy dark scalar $h'$ that mixes with the
  SM Higgs. The Wilson coefficient is
      c_r/\Lambda^3 ~ (alpha/pi v) * y_{chi H} / m_h^2 * F_loop,
  with y_{chi H} = (m_chi/v') * sin(theta). This maps the halo $\Lambda$
  bound onto the (sin theta, m_{h'}) plane at a fiducial m_chi.

* **Kinetically-mixed dark photon** — anapole/charge-radius operators are
  generated at low energy by integrating out a heavy dark photon A' with
  kinetic mixing epsilon. The Wilson coefficient is
      c_{r,a}/\Lambda^2 ~ epsilon * g_chi / M_{A'}^2,
  which maps the halo $\Lambda$ bound onto the (epsilon, M_{A'}) plane at
  fiducial g_chi.

Every existing constraint region on both planes is overlaid: for the dark
Higgs, LHC signal-strength limits on |sin theta| and the LEP mass-mixing
ceiling; for the dark photon, BaBar / NA64 / LHCb visible-mode limits and the
SN1987A energy-loss bound. The halo curve is drawn as a solid black line on
top so the "novel channel, non-competitive bound" story of the paper is
visually obvious.

Usage
-----
    python make_uv_translation_bounds.py --style paper \
        --fig-width 7.05 --fig-height 3.4 --base-fontsize 10 --linewidth 1.4

Runs standalone; the master orchestrator (make_paper_results_figures.py)
adds a --only 6 dispatch that just forwards its geometry args.
"""

from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
from matplotlib.lines import Line2D
from matplotlib.patches import Patch

_HERE = Path(__file__).resolve().parent
_ROOT = _HERE.parent
sys.path.insert(0, str(_ROOT))
sys.path.insert(0, str(_HERE))

from helpers.trinity_plotting import save_figure, set_paper_style  # noqa: E402


OUTPUT_DIR = _HERE / "plots"
BOUNDARY_DIR = _HERE / "constraint_boundaries"

# Colour palette — mirrors make_paper_style_operator_overlays so the
# translation plot reads as part of the same set.
COL_THIS = "black"
COL_COLLIDER = "#FF7AC6"
COL_BEAMDUMP = "#FFD25E"
COL_ASTRO    = "#71D6FF"
COL_PERTURB  = "#B18CFF"

# Physical constants
V_EW    = 246.0          # SM Higgs vev [GeV]
ALPHA   = 1.0 / 137.036
G_STAR  = 1.0            # generic dark-sector gauge coupling for the translation


# =============================================================================
# Halo-derived scattering bound → Λ_R (scalar Rayleigh) and Λ_a (anapole)
# =============================================================================

def _load_halo_lambda(operator_key: str, dm_type: str,
                       profile: str = "pixelwise_global_rho2",
                       majorana: bool = False) -> tuple[np.ndarray, np.ndarray]:
    """Return the (m_chi, Lambda) 90 %CL boundary produced by the pixelwise
    halo pipeline for the named operator."""
    tag_maj = "_majorana" if majorana else ""
    fname = (f"mcmc_{profile}_halo_raw_attenuation_"
             f"{dm_type}_{operator_key}{tag_maj}_90cl.npz")
    path = BOUNDARY_DIR / fname
    if not path.exists():
        raise FileNotFoundError(f"boundary file not found: {path}")
    d = np.load(path, allow_pickle=True)
    m = np.asarray(d["mchi_GeV"], dtype=float)
    L = np.asarray(d["lambda_plot_GeV"], dtype=float)
    order = np.argsort(m)
    m, L = m[order], L[order]
    finite = np.isfinite(m) & np.isfinite(L) & (m > 0) & (L > 0)
    return m[finite], L[finite]


def dark_higgs_bound(m_hprime_GeV: np.ndarray,
                       m_chi_GeV: float = 500.0,
                       vp_GeV: float = 246.0) -> np.ndarray:
    """Return the halo 90 %CL upper bound on |sin theta| as a function of m_h'.

    The scalar-Rayleigh Wilson coefficient generated by the dark-Higgs portal
    (Eq. dh_to_rayleigh of the paper) is
        c_r / Lambda^3 = (alpha / pi v) * (y_chi H / m_h'^2) * F_loop,
    with y_chi H = (m_chi / v') * sin(theta). The halo bound sets an upper
    limit on c_r / Lambda^3. Inverting for sin(theta):

        |sin theta|_max = (pi v_ew v') / (alpha F_loop m_chi) *
                          m_h'^2 / Lambda_R^3.

    Reads the scalar-Rayleigh halo bound Lambda_R(m_chi_ref) from the boundary
    npz and evaluates the RHS on the m_h' grid at m_chi = m_chi_ref.
    """
    m_grid, lam_grid = _load_halo_lambda("scalar_rayleigh", "scalar")
    # Closest halo bound to the fiducial scatterer mass.
    idx = int(np.argmin(np.abs(m_grid - m_chi_GeV)))
    lam_R = float(lam_grid[idx])
    F_loop = 1.0  # O(1) loop factor; absorbed into the definition of the ceiling.
    m_hp = np.asarray(m_hprime_GeV, dtype=float)
    sin_max = (np.pi * V_EW * vp_GeV) / (ALPHA * F_loop * m_chi_GeV) * (m_hp ** 2) / (lam_R ** 3)
    return sin_max


def dark_photon_bound(M_Aprime_GeV: np.ndarray,
                        m_chi_GeV: float = 500.0,
                        g_chi: float = 1.0) -> np.ndarray:
    """Return the halo 90 %CL upper bound on |epsilon| as a function of M_A'.

    The Dirac anapole / charge radius Wilson coefficient generated by a
    kinetically-mixed dark photon (Eq. darkphoton_to_dim6 of the paper) is
        c_{r,a} / Lambda^2 ~ epsilon * g_chi / M_A'^2.
    Inverting for epsilon:
        |epsilon|_max = (M_A'^2 / g_chi) / Lambda_a^2.
    """
    raise RuntimeError(
        "Not applicable: the anapole/charge-radius operators couple through "
        "d^nu F_nu_mu, whose on-shell photon vertex vanishes identically -- the "
        "tree-level gamma chi -> gamma chi cross section is exactly zero, so halo "
        "attenuation places no bound on (epsilon, M_A'). See Sec. V.C."
    )


# =============================================================================
# External-limits envelopes (analytic approximations, from published fits)
# =============================================================================

def lhc_higgs_signal_strength() -> float:
    """LHC combined signal-strength constraint on the Higgs-portal mixing angle,
    |sin theta| <= 0.33 at 95 %CL — ATLAS + CMS Run-2 (Refs. ATLASHiggs2022,
    CMSHiggs2022)."""
    return 0.33


def dark_photon_babar_bound(M_Aprime_GeV: np.ndarray) -> np.ndarray:
    """Coarse BaBar visible-mode envelope: epsilon <= 1e-3 for
    M_A' in [0.02, 10] GeV, rising as (M_A'/10 GeV)^0.5 above 10 GeV."""
    M = np.asarray(M_Aprime_GeV, dtype=float)
    env = 1e-3 * np.ones_like(M)
    env = np.where(M > 10.0, 1e-3 * np.sqrt(M / 10.0), env)
    env = np.where((M < 0.02) | (M > 1e3), np.nan, env)
    return env


def dark_photon_na64_bound(M_Aprime_GeV: np.ndarray) -> np.ndarray:
    """Coarse NA64 invisible-mode envelope: epsilon <= 5e-4 for
    M_A' in [1 MeV, 1 GeV]."""
    M = np.asarray(M_Aprime_GeV, dtype=float)
    env = 5e-4 * np.ones_like(M)
    env = np.where((M < 1e-3) | (M > 1.0), np.nan, env)
    return env


def dark_photon_sn1987a_bound(M_Aprime_GeV: np.ndarray) -> np.ndarray:
    """Coarse SN1987A energy-loss envelope: epsilon <= 1e-6 for
    M_A' in [1e-3, 1e-1] GeV."""
    M = np.asarray(M_Aprime_GeV, dtype=float)
    env = 1e-6 * np.ones_like(M)
    env = np.where((M < 1e-3) | (M > 1e-1), np.nan, env)
    return env


# =============================================================================
# Panels
# =============================================================================

def draw_dark_higgs_panel(ax, m_chi_GeV=500.0, base_fs=10, linewidth=1.4):
    m_hp = np.logspace(-1, 3.5, 200)  # 0.1 GeV – 3 TeV
    sin_max = dark_higgs_bound(m_hp, m_chi_GeV=m_chi_GeV)
    ax.loglog(m_hp, sin_max, color=COL_THIS, lw=linewidth * 1.4,
              label=f"Halo scattering (this work), $m_\\chi = {m_chi_GeV:.0f}$ GeV")

    # LHC signal-strength ceiling
    sin_lhc = lhc_higgs_signal_strength()
    ax.axhline(sin_lhc, color=COL_COLLIDER, lw=linewidth, ls="-",
               label=f"LHC $\\sin\\theta \\leq {sin_lhc}$ (ATLAS/CMS)")
    ax.fill_between(m_hp, sin_lhc, 10, color=COL_COLLIDER, alpha=0.15)

    # Perturbativity ceiling: y_chi = sin(theta) * m_chi / v' <= sqrt(4 pi).
    y_pert = np.sqrt(4 * np.pi)
    sin_pert = y_pert * V_EW / m_chi_GeV
    ax.axhline(min(sin_pert, 1.0), color=COL_PERTURB, lw=linewidth, ls=":",
               label=r"Perturbativity ($y_\chi = \sqrt{4\pi}$)")

    ax.set_xlim(1e-3, 3e3)
    ax.set_ylim(1e-6, 1e12)
    ax.set_xlabel(r"$m_{h'}$ [GeV]", fontsize=base_fs)
    ax.set_ylabel(r"$|\sin\theta|$", fontsize=base_fs)
    ax.set_title(r"Dark-Higgs portal", fontsize=base_fs + 1)
    ax.tick_params(labelsize=base_fs - 2)
    ax.grid(True, which="both", alpha=0.2)
    ax.legend(fontsize=base_fs - 1, loc="lower right",
              frameon=True, framealpha=0.6, facecolor="white", edgecolor="0.7",
              borderpad=0.4, handlelength=2.4, handletextpad=0.5,
              labelspacing=0.4)


def ew_doublet_dipole_bound():
    """Halo 90%CL upper bound on the DM magnetic dipole moment mu(m_chi).

    The dipole Compton cross section depends only on mu = 2 c_M/Lambda, so
    the halo boundary Lambda(m_chi) at c_M = 1 converts directly to an
    excluded dipole moment mu >= 2/Lambda.
    Returns (m_grid [GeV], mu_bound [GeV^-1]).
    """
    m_grid, lam_grid = _load_halo_lambda("dipole_magnetic", "fermionic")
    return m_grid, 2.0 / lam_grid


def ew_doublet_dipole_prediction(m_chi_GeV):
    """Parametric one-loop magnetic dipole of a Dirac electroweak doublet
    (higgsino-like), mu ~ e g^2 / (64 pi^2 m_chi) for m_chi >> m_W, with the
    O(1) loop function set to unity.  [GeV^-1]"""
    e_em = np.sqrt(4.0 * np.pi * ALPHA)
    g_su2 = 0.65
    return e_em * g_su2**2 / (64.0 * np.pi**2 * np.asarray(m_chi_GeV, dtype=float))


def draw_ew_doublet_panel(ax, base_fs=10, linewidth=1.4,
                          mann_window=(550.0, 720.0), col_coll=COL_COLLIDER, col_this=COL_THIS):
    """(m_chi, mu) plane: halo dipole-attenuation bound vs the one-loop dipole
    of a Dirac electroweak doublet -- the higgsino-like candidate class the
    companion halo fit prefers."""
    m_b, mu_b = ew_doublet_dipole_bound()
    ax.loglog(m_b, mu_b, color=col_this, lw=linewidth * 1.4,
              label="Halo attenuation (this work)")

    # CMB dipole boundary (same mu = 2/Lambda conversion).
    #
    # The Planck CMB dipole bound is genuinely off-scale for the (m_chi, mu)
    # window shown here, so it is intentionally not drawn (and no legend entry
    # is emitted, to avoid advertising a curve that never appears in the
    # frame).  The Boddy & Gluscevic (2018) bound is applied by
    # constraint_generation/cmb_constraints.py at the CMB temperature
    # E = T_CMB0 ~ 2.3e-13 GeV, where the n=2 dipole cross section is so
    # suppressed that the excluded scale is Lambda ~ 1e-13-1e-5 GeV, i.e.
    # mu = 2/Lambda ~ 1e5-1e12 GeV^-1 -- three to ten decades above the top of
    # this panel (ylim = 1e-8..1e3).  The CMB dipole bound only becomes
    # competitive for m_chi < few MeV, off the left edge of this GeV-TeV panel.
    # The curve is only overlaid if it actually intersects the plotted
    # mu-range; otherwise it is omitted rather than shown as an invisible
    # off-frame line.
    cmb_path = BOUNDARY_DIR / "cmb_fermionic_dipole_magnetic_planck2018.npz"
    if cmb_path.exists():
        d = np.load(cmb_path, allow_pickle=True)
        m_c = np.asarray(d["mchi_GeV"], dtype=float)
        lam_c = np.asarray(d["lambda_plot_GeV"], dtype=float)
        ok = (np.isfinite(m_c) & np.isfinite(lam_c) & (lam_c > 0)
              & (m_c >= 1e0) & (m_c <= 1e4))
        mu_c = 2.0 / lam_c[ok]
        # Only draw + label if any point lands inside the panel's mu window.
        if np.any((mu_c >= 1e-8) & (mu_c <= 1e3)):
            ax.loglog(m_c[ok], mu_c, color=COL_ASTRO, lw=linewidth,
                      ls="--", label="CMB (Planck 2018)")
        else:
            print("  [Fig5 right] CMB dipole bound off-scale for this "
                  "(m_chi, mu) window -- omitted (mu = 2/Lambda ~ "
                  f"{np.nanmin(mu_c):.1e}-{np.nanmax(mu_c):.1e} GeV^-1).")

    m_grid = np.logspace(0, 4, 200)
    ax.loglog(m_grid, ew_doublet_dipole_prediction(m_grid),
              color=col_coll, lw=linewidth, ls="-",
              label=r"EW doublet, $\mu \sim e g^{2}/64\pi^{2} m_\chi$")

    ax.axvspan(*mann_window, color=COL_BEAMDUMP, alpha=0.35, zorder=0,
               label=r"Halo best-fit $m_\chi^{\rm ann}$")

    ax.set_xlim(1e0, 1e4)
    ax.set_ylim(1e-8, 1e3)
    ax.set_xlabel(r"$m_\chi$ [GeV]", fontsize=base_fs)
    ax.set_ylabel(r"$\mu$ [GeV$^{-1}$]", fontsize=base_fs)
    ax.set_title(r"Electroweak-doublet dipole", fontsize=base_fs + 1)
    ax.tick_params(labelsize=base_fs - 2)
    ax.grid(True, which="both", alpha=0.2)
    # Below-plot legend -- matches the left (dark-Higgs) panel's FIG5_LEGEND_KW
    # layout in make_paper_results_figures.py so both halves of Fig 5 read the
    # same way (same fontsize, same anchor below the axes, same 2-column grid).
    ax.legend(fontsize=base_fs - 1, loc="upper center",
              bbox_to_anchor=(0.5, -0.2), ncol=1,
              frameon=True, framealpha=0.6, facecolor="white", edgecolor="0.7",
              borderpad=0.35, handlelength=2.0, handletextpad=0.45,
              columnspacing=0.9, labelspacing=0.30)


def draw_dark_photon_panel(ax, m_chi_GeV=500.0, base_fs=10, linewidth=1.4):
    M_Ap = np.logspace(-3, 2, 200)  # 1 MeV – 100 GeV
    eps_max = dark_photon_bound(M_Ap, m_chi_GeV=m_chi_GeV, g_chi=G_STAR)
    ax.loglog(M_Ap, eps_max, color=COL_THIS, lw=linewidth * 1.4,
              label=f"Halo scattering (this work), $m_\\chi = {m_chi_GeV:.0f}$ GeV")

    # BaBar / NA64 / SN1987A envelopes
    ax.loglog(M_Ap, dark_photon_babar_bound(M_Ap), color=COL_COLLIDER, lw=linewidth,
              label="BaBar (visible mode)")
    ax.loglog(M_Ap, dark_photon_na64_bound(M_Ap), color=COL_BEAMDUMP, lw=linewidth,
              label="NA64 (invisible mode)")
    ax.loglog(M_Ap, dark_photon_sn1987a_bound(M_Ap), color=COL_ASTRO, lw=linewidth,
              ls="--", label="SN1987A (energy loss)")

    ax.set_xlim(1e-3, 1e2)
    ax.set_ylim(1e-8, 1e4)
    ax.set_xlabel(r"$M_{A'}$ [GeV]", fontsize=base_fs)
    ax.set_ylabel(r"$|\epsilon|$", fontsize=base_fs)
    ax.set_title(r"Kinetically mixed dark photon", fontsize=base_fs + 1)
    ax.tick_params(labelsize=base_fs - 2)
    ax.grid(True, which="both", alpha=0.2)
    ax.legend(fontsize=base_fs - 1, loc="lower right",
              frameon=True, framealpha=0.6, facecolor="white", edgecolor="0.7",
              borderpad=0.4, handlelength=2.4, handletextpad=0.5,
              labelspacing=0.4)


# =============================================================================
# Entry point
# =============================================================================

def main(argv=None) -> int:
    p = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--outfile", default="uv_translation_bounds",
                   help="Basename for the output PDF/PNG (default: uv_translation_bounds)")
    p.add_argument("--style", default="paper")
    p.add_argument("--fig-width", type=float, default=7.05)
    p.add_argument("--fig-height", type=float, default=3.4)
    p.add_argument("--base-fontsize", type=float, default=10)
    p.add_argument("--linewidth", type=float, default=1.4)
    p.add_argument("--mchi", type=float, default=500.0,
                   help="Fiducial scatterer mass (GeV) at which the halo bound is read off.")
    args = p.parse_args(argv)

    if args.style:
        os.environ["TRINITY_PLOT_STYLE"] = args.style
    set_paper_style(base_fontsize=args.base_fontsize, linewidth=args.linewidth,
                    n_colors=14, cmap_name="plasma")

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    # Dark-photon panel omitted (anapole/CR real-photon amplitude is exactly
    # zero at tree level -- no halo bound exists on (epsilon, M_A')). Shown
    # instead: the electroweak-doublet dipole panel.
    fig, (ax_h, ax_d) = plt.subplots(1, 2, figsize=(args.fig_width, args.fig_height))
    draw_dark_higgs_panel(ax_h, m_chi_GeV=args.mchi,
                          base_fs=args.base_fontsize, linewidth=args.linewidth)
    draw_ew_doublet_panel(ax_d, base_fs=args.base_fontsize, linewidth=args.linewidth)
    fig.tight_layout()
    fig.subplots_adjust(wspace=0.22)

    save_figure(fig, str(OUTPUT_DIR / args.outfile))
    fig.savefig(str(OUTPUT_DIR / f"{args.outfile}.pdf"), bbox_inches="tight")
    plt.close(fig)
    print(f"Saved UV translation bounds: {OUTPUT_DIR / args.outfile}.{{png,pdf}}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
